name: Deploy Tenangin Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/Tenangin-Backend || { git clone https://github.com/syahrul-awaludin/Tenangin-Backend.git ~/Tenangin-Backend && cd ~/Tenangin-Backend; }
            git pull origin main
            npm install --omit=dev
            npx prisma generate
            npx prisma db push --accept-data-loss
            pm2 restart tenangin-backend || pm2 start src/index.js --name "tenangin-backend" --update-env
